version: '3.7'
services:
  react:
    container_name: dailyreport_front
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    tty: true
    volumes:
      - ./app:/app
  fastapi:
    container_name: dailyreport_back
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
    ports:
      - 8000:8000
    restart: always
    tty: true
    volumes:
      - ./app/back:/app
  mariadb:
    image: mariadb:latest
    container_name: dailyreport_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dailyreport-db
      MYSQL_USER: dailyreport
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
